--
-- PostgreSQL database dump
--

\restrict fNjee38f5Ds4I0wG0uBag6BvOm1fzfr2D6LsZ6QFN0d2AGJoNHVYHZTrX57DVHg

-- Dumped from database version 18.6
-- Dumped by pg_dump version 18.6

-- Started on 2026-09-10 15:12:46

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 221 (class 1259 OID 16421)
-- Name: saved_locations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.saved_locations (
    id bigint NOT NULL,
    user_id character varying NOT NULL,
    location_name character varying,
    latitude double precision,
    longitude double precision
);


ALTER TABLE public.saved_locations OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 24576)
-- Name: saved_locations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.saved_locations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.saved_locations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 219 (class 1259 OID 16389)
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id character varying NOT NULL,
    name character varying(100) NOT NULL,
    email character varying(150) NOT NULL,
    user_type character varying(50),
    location character varying,
    latitude double precision,
    longitude double precision
);


ALTER TABLE public.users OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 16400)
-- Name: weather_preferences; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.weather_preferences (
    id bigint NOT NULL,
    user_id character varying NOT NULL,
    temperature boolean,
    precipitation boolean,
    humidity boolean,
    wind_speed boolean,
    uv_index boolean
);


ALTER TABLE public.weather_preferences OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 24577)
-- Name: weather_preferences_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.weather_preferences ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.weather_preferences_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 5022 (class 0 OID 16421)
-- Dependencies: 221
-- Data for Name: saved_locations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.saved_locations (id, user_id, location_name, latitude, longitude) FROM stdin;
\.


--
-- TOC entry 5020 (class 0 OID 16389)
-- Dependencies: 219
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id, name, email, user_type, location, latitude, longitude) FROM stdin;
\.


--
-- TOC entry 5021 (class 0 OID 16400)
-- Dependencies: 220
-- Data for Name: weather_preferences; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.weather_preferences (id, user_id, temperature, precipitation, humidity, wind_speed, uv_index) FROM stdin;
\.


--
-- TOC entry 5030 (class 0 OID 0)
-- Dependencies: 222
-- Name: saved_locations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.saved_locations_id_seq', 1, false);


--
-- TOC entry 5031 (class 0 OID 0)
-- Dependencies: 223
-- Name: weather_preferences_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.weather_preferences_id_seq', 1, false);


--
-- TOC entry 4870 (class 2606 OID 16429)
-- Name: saved_locations saved_locations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.saved_locations
    ADD CONSTRAINT saved_locations_pkey PRIMARY KEY (id);


--
-- TOC entry 4866 (class 2606 OID 16399)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- TOC entry 4868 (class 2606 OID 16406)
-- Name: weather_preferences weather_preferences_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.weather_preferences
    ADD CONSTRAINT weather_preferences_pkey PRIMARY KEY (id);


--
-- TOC entry 4872 (class 2606 OID 16430)
-- Name: saved_locations fk_saved_locations_user; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.saved_locations
    ADD CONSTRAINT fk_saved_locations_user FOREIGN KEY (user_id) REFERENCES public.users(id) NOT VALID;


--
-- TOC entry 4871 (class 2606 OID 16416)
-- Name: weather_preferences fk_weather_preferences_user; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.weather_preferences
    ADD CONSTRAINT fk_weather_preferences_user FOREIGN KEY (user_id) REFERENCES public.users(id) NOT VALID;


-- Completed on 2026-09-10 15:12:46

--
-- PostgreSQL database dump complete
--

\unrestrict fNjee38f5Ds4I0wG0uBag6BvOm1fzfr2D6LsZ6QFN0d2AGJoNHVYHZTrX57DVHg

